apiVersion: apps/v1
kind: Deployment
metadata:
  name: espray-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: espray-backend
          resources:
            requests:
              memory: 500Mi
            limits:
              memory: 500Mi
          ports:
            - containerPort: 80
              $patch: delete
            - name: http
              containerPort: 7010
          args: ["--spring.profiles.active=qa"]
