apiVersion: apps/v1
kind: Deployment
metadata:
  name: espray-backend
spec:
  selector:
    matchLabels:
      app: espray
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: espray
        tier: backend
    spec:
      containers:
        - name: espray-backend
          image: "espray:latest"
          ports:
            - name: http
              containerPort: 80


