apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: compass-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
#  tls:
#  - hosts:
#    - compass.qualix.ai
#    secretName: qualix-tls
