apiVersion: apps/v1
kind: Deployment
metadata:
  name: compass-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: compass-backend
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 1Gi
          ports:
            - containerPort: 80
              $patch: delete
            - name: http
              containerPort: 9955
          args: ["--spring.profiles.active=qa"]
