apiVersion: apps/v1
kind: Deployment
metadata:
  name: compass-frontend
spec:
  selector:
    matchLabels:
      app: compass
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: compass
        tier: frontend
    spec:
      containers:
        - name: compass-frontend
          image: "compass/frontend:latest"
          ports:
            - name: http
              containerPort: 80


