apiVersion: apps/v1
kind: Deployment
metadata:
  name: chilly-frontend
spec:
  selector:
    matchLabels:
      app: chilly
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: chilly
        tier: frontend
    spec:
      containers:
        - name: chilly-frontend
          image: "chilly/frontend:latest"
          ports:
            - name: http
              containerPort: 80


